config/routes.rb
Rails.application.routes.draw do
  resources :mail_types

  # Explicit email routes (resources :emails should generate these, but adding explicitly)
  get    'emails'          => 'emails#index',   as: 'emails'
  post   'emails'          => 'emails#create'
  get    'emails/new'      => 'emails#new',     as: 'new_email'
  get    'emails/:id'      => 'emails#show',    as: 'email'
  get    'emails/:id/edit' => 'emails#edit',    as: 'edit_email'
  patch  'emails/:id'      => 'emails#update'
  put    'emails/:id'      => 'emails#update'
  delete 'emails/:id'      => 'emails#destroy'

  get 'resend_email'                        => 'emails#resend_email'
  post 'resend_emails'                       => 'emails#resend_emails'
   
      
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ResqueWeb::Engine => "/resque_web"
end

app/controllers/mail_types_controller.rb
class MailTypesController < ApplicationController
  before_action :set_mail_type, only: [:show, :edit, :update, :destroy]

  # GET /mail_types
  # GET /mail_types.json
  def index
    @mail_types = MailType.all
  end

  # GET /mail_types/1
  # GET /mail_types/1.json
  def show
  end

  # GET /mail_types/new
  def new
    @mail_type = MailType.new
  end

  # GET /mail_types/1/edit
  def edit
  end

  # POST /mail_types
  # POST /mail_types.json
  def create
    @mail_type = MailType.new(mail_type_params)

    respond_to do |format|
      if @mail_type.save
        format.html { redirect_to @mail_type, notice: 'Mail type was successfully created.' }
        format.json { render :show, status: :created, location: @mail_type }
      else
        format.html { render :new }
        format.json { render json: @mail_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mail_types/1
  # PATCH/PUT /mail_types/1.json
  def update
    respond_to do |format|
      if @mail_type.update(mail_type_params)
        format.html { redirect_to @mail_type, notice: 'Mail type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mail_type }
      else
        format.html { render :edit }
        format.json { render json: @mail_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_types/1
  # DELETE /mail_types/1.json
  def destroy
    @mail_type.destroy
    respond_to do |format|
      format.html { redirect_to mail_types_url, notice: 'Mail type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mail_type
      @mail_type = MailType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mail_type_params
      params.require(:mail_type).permit(:name, :description, :schedule)
    end
end

app/helpers/mail_types_helper.rb
module MailTypesHelper
end

app/views/mail_types/_form.html.erb
<%= form_for(mail_type) do |f| %>
  <% if mail_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mail_type.errors.count, "error") %> prohibited this mail_type from being saved:</h2>

      <ul>
      <% mail_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :schedule %>
    <%= f.datetime_select :schedule %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mail_types/edit.html.erb
<h1>Editing Mail Type</h1>

<%= render 'form', mail_type: @mail_type %>

<%= link_to 'Show', @mail_type %> |
<%= link_to 'Back', mail_types_path %>

app/views/mail_types/index.html.erb
<h1>Mail Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mail_types.each do |mail_type| %>
      <tr>
        <td><%= mail_type.name %></td>
        <td><%= mail_type.description %></td>
        <td><%= mail_type.schedule %></td>
        <td><%= link_to 'Show', mail_type %></td>
        <td><%= link_to 'Edit', edit_mail_type_path(mail_type) %></td>
        <td><%= link_to 'Destroy', mail_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mail Type', new_mail_type_path %>

app/views/mail_types/new.html.erb
<h1>New Mail Type</h1>

<%= render 'form', mail_type: @mail_type %>

<%= link_to 'Back', mail_types_path %>

app/views/mail_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @mail_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mail_type.description %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @mail_type.schedule %>
</p>

<%= link_to 'Edit', edit_mail_type_path(@mail_type) %> |
<%= link_to 'Back', mail_types_path %>